// angular-client/src/app/pages/chat/chat.component.ts
import { Component, inject, signal, computed, effect, ElementRef, ViewChild, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ApiService, Conversation, Message } from '../../services/api.service';
import { ToastService } from '../../services/toast.service';

const AI_MODELS = [
  { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', desc: 'Schnell & ausgewogen (Google)', tier: 'free', icon: '🔵' },
  { id: 'gpt-4o-mini', name: 'GPT-4o Mini', desc: 'Kostengünstig (OpenAI)', tier: 'free', icon: '🟢' },
  { id: 'deepseek/deepseek-r1:free', name: 'DeepSeek R1 (Free)', desc: 'Reasoning & Logik', tier: 'free', icon: '🟣' },
  { id: 'google/gemini-2.0-flash:free', name: 'Gemini 2.0 Flash', desc: 'Neueste Version', tier: 'free', icon: '🔵' },
  { id: 'gpt-4o', name: 'GPT-4o', desc: 'Omni-Modell (OpenAI)', tier: 'ultra', icon: '🟢' },
  { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', desc: 'Erweiterte Fähigkeiten', tier: 'ultra', icon: '🔵' },
  { id: 'deepseek-chat', name: 'DeepSeek Chat', desc: 'Kostengünstig & stark', tier: 'ultra', icon: '🟣' },
  { id: 'gpt-5', name: 'GPT-5', desc: 'Neuestes OpenAI-Modell', tier: 'pro', icon: '⭐' },
];

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <div class="chat-layout">
      <!-- Sidebar -->
      <aside class="sidebar">
        <div class="sidebar-header">
          <a routerLink="/" class="sidebar-logo">
            <div class="logo-mark">W</div>
            <span>wensday.ch</span>
          </a>
          @if (auth.isAuthenticated()) {
            <button class="btn btn-primary new-chat-btn" (click)="newConversation()">
              + Neues Gespräch
            </button>
          } @else {
            <div class="guest-banner">
              <p>Free Chat</p>
              <button class="btn btn-primary" style="width:100%;font-size:0.8rem" (click)="auth.login()">
                Anmelden für mehr
              </button>
            </div>
          }
        </div>

        @if (auth.isAuthenticated()) {
          <div class="conversations-list">
            @if (loadingConvs()) {
              <div style="padding:1rem;text-align:center">
                <div class="spinner" style="margin:0 auto"></div>
              </div>
            }
            @for (conv of conversations(); track conv.id) {
              <div class="conv-item" [class.active]="selectedId() === conv.id"
                   (click)="selectConversation(conv.id)">
                <div class="conv-info">
                  <div class="conv-title">{{ conv.title }}</div>
                  <div class="conv-date">{{ formatDate(conv.updatedAt) }}</div>
                </div>
                <button class="conv-delete" (click)="deleteConv($event, conv.id)">✕</button>
              </div>
            }
          </div>
        }

        <div class="sidebar-footer">
          @if (auth.isAuthenticated()) {
            <div class="user-info">
              @if (auth.user()?.profileImageUrl) {
                <img [src]="auth.user()!.profileImageUrl" class="user-avatar" alt="Profil">
              } @else {
                <div class="user-avatar-fallback">
                  {{ (auth.user()?.firstName?.[0] || 'U') | uppercase }}
                </div>
              }
              <div class="user-details">
                <div class="user-name">{{ auth.user()?.firstName || auth.user()?.email }}</div>
                <div class="user-tier" [class]="'tier-' + (auth.user()?.subscriptionTier || 'free')">
                  {{ getTierLabel() }}
                </div>
              </div>
            </div>
          }
          <div class="sidebar-brand">KI-Chat by wensday.ch</div>
        </div>
      </aside>

      <!-- Main Chat -->
      <main class="chat-main">
        @if (showChat()) {
          <!-- Model selector -->
          <div class="model-bar">
            <label class="model-label">🧠 KI-Modell:</label>
            <select class="select model-select" [(ngModel)]="selectedModel">
              @for (model of availableModels(); track model.id) {
                <option [value]="model.id" [disabled]="!canUseModel(model.tier)">
                  {{ model.icon }} {{ model.name }}
                  {{ !canUseModel(model.tier) ? ' (' + model.tier + ')' : '' }}
                </option>
              }
            </select>
            <span class="model-info">Multi-AI ⚡</span>
          </div>

          <!-- Messages -->
          <div class="messages-area" #messagesArea>
            @if (!auth.isAuthenticated()) {
              <div class="guest-notice">
                <strong>Free Chat</strong> – Melde dich an für gespeicherte Gespräche und mehr Funktionen.
              </div>
            }

            @for (msg of displayMessages(); track $index) {
              <div class="message-row" [class.user]="msg.role === 'user'">
                @if (msg.role === 'assistant') {
                  <div class="msg-avatar-icon ai">W</div>
                }
                <div class="message-bubble" [class.user-bubble]="msg.role === 'user'" [class.ai-bubble]="msg.role === 'assistant'">
                  <p class="msg-text">{{ msg.content }}</p>
                  @if (msg.role === 'assistant') {
                    <div class="msg-meta">
                      @if (msg.aiModel) { <span class="msg-model">{{ msg.aiModel }}</span> }
                    </div>
                  }
                </div>
                @if (msg.role === 'user') {
                  <div class="msg-avatar-icon user">{{ (auth.user()?.firstName?.[0] || 'U') | uppercase }}</div>
                }
              </div>
            }

            @if (generating()) {
              <div class="message-row">
                <div class="msg-avatar-icon ai">W</div>
                <div class="ai-bubble message-bubble">
                  <div class="typing-dots">
                    <span class="dot-1">●</span>
                    <span class="dot-2">●</span>
                    <span class="dot-3">●</span>
                  </div>
                </div>
              </div>
            }
            <div #bottomAnchor></div>
          </div>

          <!-- Input -->
          <div class="input-area">
            <div class="input-inner">
              <input
                class="input chat-input"
                [(ngModel)]="newMessage"
                (keydown.enter)="sendMessage()"
                placeholder="Nachricht eingeben..."
                [disabled]="generating()"
              />
              <button class="btn btn-primary send-btn"
                      (click)="sendMessage()"
                      [disabled]="!newMessage.trim() || generating()">
                ➤
              </button>
            </div>
            <p class="input-hint">Enter zum Senden · wensday.ch · Swiss AI</p>
          </div>
        } @else {
          <!-- Welcome screen -->
          <div class="welcome-screen">
            <div class="welcome-icon">🧠</div>
            <h2>Willkommen bei wensday.ch</h2>
            <p>Starten Sie ein neues Gespräch oder wählen Sie eine bestehende Unterhaltung.</p>
            <button class="btn btn-primary" (click)="newConversation()">
              + Neues Gespräch starten
            </button>
          </div>
        }
      </main>
    </div>
  `,
  styles: [`
    .chat-layout {
      display: flex;
      height: 100vh;
      overflow: hidden;
      background: white;
    }
    /* Sidebar */
    .sidebar {
      width: 280px;
      background: #f9fafb;
      border-right: 1px solid var(--border);
      display: flex;
      flex-direction: column;
      flex-shrink: 0;
    }
    .sidebar-header {
      padding: 1rem;
      border-bottom: 1px solid var(--border);
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
    }
    .sidebar-logo {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      text-decoration: none;
      color: var(--foreground);
      font-weight: 700;
    }
    .logo-mark {
      width: 1.75rem;
      height: 1.75rem;
      background: var(--lopez-green);
      border-radius: 0.375rem;
      color: white;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 0.75rem;
      font-weight: 700;
    }
    .new-chat-btn { font-size: 0.8125rem; }
    .guest-banner { text-align: center; }
    .guest-banner p { font-size: 0.875rem; font-weight: 600; margin-bottom: 0.5rem; }
    .conversations-list {
      flex: 1;
      overflow-y: auto;
      padding: 0.5rem;
    }
    .conv-item {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.625rem 0.75rem;
      border-radius: 0.5rem;
      cursor: pointer;
      transition: background 0.15s;
      margin-bottom: 0.25rem;
    }
    .conv-item:hover { background: #f3f4f6; }
    .conv-item.active { background: #e5e7eb; }
    .conv-info { flex: 1; min-width: 0; }
    .conv-title {
      font-size: 0.8125rem;
      font-weight: 500;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .conv-date { font-size: 0.6875rem; color: var(--swiss-gray); margin-top: 0.125rem; }
    .conv-delete {
      opacity: 0;
      background: none;
      border: none;
      cursor: pointer;
      color: var(--swiss-gray);
      font-size: 0.75rem;
      padding: 0.25rem;
      border-radius: 0.25rem;
      transition: opacity 0.15s, color 0.15s;
    }
    .conv-item:hover .conv-delete { opacity: 1; }
    .conv-delete:hover { color: #ef4444; }
    .sidebar-footer {
      padding: 1rem;
      border-top: 1px solid var(--border);
    }
    .user-info {
      display: flex;
      align-items: center;
      gap: 0.625rem;
      margin-bottom: 0.75rem;
    }
    .user-avatar {
      width: 2rem;
      height: 2rem;
      border-radius: 50%;
      object-fit: cover;
    }
    .user-avatar-fallback {
      width: 2rem;
      height: 2rem;
      background: var(--lopez-green);
      color: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 0.75rem;
      font-weight: 700;
    }
    .user-name { font-size: 0.8125rem; font-weight: 600; }
    .user-tier { font-size: 0.6875rem; font-weight: 500; }
    .tier-free { color: var(--swiss-gray); }
    .tier-ultra { color: #7c3aed; }
    .tier-pro { color: #d97706; }
    .sidebar-brand { font-size: 0.6875rem; color: var(--swiss-gray); text-align: center; }
    /* Main */
    .chat-main {
      flex: 1;
      display: flex;
      flex-direction: column;
      overflow: hidden;
    }
    .model-bar {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      padding: 0.75rem 1.5rem;
      border-bottom: 1px solid var(--border);
      background: white;
    }
    .model-label { font-size: 0.875rem; font-weight: 500; color: var(--swiss-gray); white-space: nowrap; }
    .model-select { width: 260px; }
    .model-info { font-size: 0.75rem; color: var(--swiss-gray); margin-left: auto; }
    .messages-area {
      flex: 1;
      overflow-y: auto;
      padding: 1.5rem;
    }
    .guest-notice {
      text-align: center;
      padding: 0.75rem 1.25rem;
      background: var(--swiss-light);
      border-radius: 0.75rem;
      font-size: 0.8125rem;
      color: var(--swiss-gray);
      margin-bottom: 1.5rem;
    }
    .message-row {
      display: flex;
      gap: 0.75rem;
      align-items: flex-end;
      margin-bottom: 1.25rem;
      max-width: 800px;
      margin-left: auto;
      margin-right: auto;
    }
    .message-row.user { flex-direction: row-reverse; }
    .msg-avatar-icon {
      width: 2rem;
      height: 2rem;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 0.75rem;
      font-weight: 700;
      flex-shrink: 0;
    }
    .msg-avatar-icon.ai { background: var(--lopez-green); color: white; }
    .msg-avatar-icon.user { background: #e5e7eb; color: #374151; }
    .message-bubble {
      max-width: 70%;
      padding: 0.75rem 1rem;
      border-radius: 1.25rem;
    }
    .ai-bubble { background: #f3f4f6; color: #111827; }
    .user-bubble { background: var(--lopez-green); color: white; }
    .msg-text { font-size: 0.9375rem; line-height: 1.6; white-space: pre-wrap; margin: 0; }
    .msg-meta { margin-top: 0.375rem; display: flex; gap: 0.5rem; }
    .msg-model {
      font-size: 0.6875rem;
      color: var(--swiss-gray);
      background: white;
      padding: 0.125rem 0.5rem;
      border-radius: 9999px;
      border: 1px solid var(--border);
    }
    .typing-dots {
      display: flex;
      gap: 0.25rem;
      align-items: center;
      font-size: 0.875rem;
      color: var(--swiss-gray);
    }
    .typing-dots span { animation: bounce 1s infinite; }
    .dot-1 { animation-delay: 0s !important; }
    .dot-2 { animation-delay: 0.2s !important; }
    .dot-3 { animation-delay: 0.4s !important; }
    @keyframes bounce {
      0%, 100% { transform: translateY(0); opacity: 0.4; }
      50% { transform: translateY(-4px); opacity: 1; }
    }
    .input-area {
      padding: 1rem 1.5rem;
      border-top: 1px solid var(--border);
      background: white;
    }
    .input-inner {
      display: flex;
      gap: 0.75rem;
      max-width: 800px;
      margin: 0 auto;
    }
    .chat-input { flex: 1; }
    .send-btn { width: 2.75rem; height: 2.75rem; padding: 0; font-size: 1rem; flex-shrink: 0; }
    .input-hint { font-size: 0.6875rem; color: var(--swiss-gray); text-align: center; margin-top: 0.5rem; }
    /* Welcome */
    .welcome-screen {
      flex: 1;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 1rem;
      padding: 2rem;
      text-align: center;
    }
    .welcome-icon { font-size: 4rem; }
    .welcome-screen h2 { font-size: 1.75rem; font-weight: 700; }
    .welcome-screen p { color: var(--swiss-gray); max-width: 360px; }
    @media (max-width: 768px) {
      .sidebar { display: none; }
    }
  `]
})
export class ChatComponent implements OnInit {
  auth = inject(AuthService);
  api = inject(ApiService);
  toast = inject(ToastService);

  @ViewChild('bottomAnchor') bottomAnchor!: ElementRef;

  conversations = signal<Conversation[]>([]);
  selectedId = signal<string | null>(null);
  messages = signal<Message[]>([]);
  guestMessages = signal<Array<{ role: 'user' | 'assistant'; content: string; aiModel?: string }>>([]);
  loadingConvs = signal(false);
  generating = signal(false);
  newMessage = '';
  selectedModel = 'gemini-2.5-flash';

  availableModels = computed(() => AI_MODELS);

  displayMessages = computed(() => {
    if (this.auth.isAuthenticated()) {
      return this.messages();
    }
    return this.guestMessages();
  });

  showChat = computed(() => {
    if (!this.auth.isAuthenticated()) return true;
    return !!this.selectedId();
  });

  constructor() {
    effect(() => {
      if (this.auth.isAuthenticated() && !this.auth.isLoading()) {
        this.loadConversations();
      }
    });
  }

  ngOnInit() {}

  async loadConversations() {
    this.loadingConvs.set(true);
    try {
      const convs = await this.api.getConversations();
      this.conversations.set(convs);
      if (convs.length > 0 && !this.selectedId()) {
        await this.selectConversation(convs[0].id);
      }
    } catch {
      this.toast.error('Fehler', 'Gespräche konnten nicht geladen werden');
    } finally {
      this.loadingConvs.set(false);
    }
  }

  async selectConversation(id: string) {
    this.selectedId.set(id);
    try {
      const msgs = await this.api.getMessages(id);
      this.messages.set(msgs);
      this.scrollToBottom();
    } catch {
      this.toast.error('Fehler', 'Nachrichten konnten nicht geladen werden');
    }
  }

  async newConversation() {
    try {
      const conv = await this.api.createConversation();
      this.conversations.update(c => [conv, ...c]);
      this.selectedId.set(conv.id);
      this.messages.set([]);
    } catch {
      this.toast.error('Fehler', 'Gespräch konnte nicht erstellt werden');
    }
  }

  async deleteConv(e: Event, id: string) {
    e.stopPropagation();
    try {
      await this.api.deleteConversation(id);
      this.conversations.update(c => c.filter(x => x.id !== id));
      if (this.selectedId() === id) {
        const remaining = this.conversations();
        if (remaining.length > 0) {
          await this.selectConversation(remaining[0].id);
        } else {
          this.selectedId.set(null);
          this.messages.set([]);
        }
      }
      this.toast.success('Gelöscht', 'Gespräch wurde entfernt');
    } catch {
      this.toast.error('Fehler', 'Gespräch konnte nicht gelöscht werden');
    }
  }

  async sendMessage() {
    if (!this.newMessage.trim() || this.generating()) return;
    const content = this.newMessage.trim();
    this.newMessage = '';
    this.generating.set(true);

    if (!this.auth.isAuthenticated()) {
      this.guestMessages.update(m => [...m, { role: 'user', content }]);
      try {
        const res = await this.api.freeChat(content, this.selectedModel);
        this.guestMessages.update(m => [...m, { role: 'assistant', content: res.response, aiModel: this.selectedModel }]);
      } catch {
        this.toast.error('Fehler', 'Nachricht konnte nicht gesendet werden');
      } finally {
        this.generating.set(false);
        this.scrollToBottom();
      }
      return;
    }

    let convId = this.selectedId();
    if (!convId) {
      try {
        const conv = await this.api.createConversation();
        this.conversations.update(c => [conv, ...c]);
        this.selectedId.set(conv.id);
        convId = conv.id;
      } catch {
        this.toast.error('Fehler', 'Konversation konnte nicht erstellt werden');
        this.generating.set(false);
        return;
      }
    }

    this.messages.update(m => [...m, {
      id: Date.now().toString(),
      conversationId: convId!,
      role: 'user',
      content
    }]);

    try {
      await this.api.sendMessage(convId!, content, this.selectedModel);
      const msgs = await this.api.getMessages(convId!);
      this.messages.set(msgs);
    } catch (err: any) {
      this.toast.error('Fehler', err?.message || 'Nachricht konnte nicht gesendet werden');
    } finally {
      this.generating.set(false);
      this.scrollToBottom();
    }
  }

  canUseModel(tier: string): boolean {
    const userTier = this.auth.user()?.subscriptionTier || 'free';
    if (tier === 'free') return true;
    if (tier === 'ultra') return ['ultra', 'pro'].includes(userTier);
    if (tier === 'pro') return userTier === 'pro';
    return false;
  }

  getTierLabel(): string {
    const tier = this.auth.user()?.subscriptionTier || 'free';
    return tier === 'free' ? 'Free' : tier === 'ultra' ? '⚡ Ultra' : '👑 Pro';
  }

  formatDate(date?: string): string {
    if (!date) return '';
    return new Date(date).toLocaleDateString('de-CH');
  }

  scrollToBottom() {
    setTimeout(() => {
      this.bottomAnchor?.nativeElement?.scrollIntoView({ behavior: 'smooth' });
    }, 100);
  }
}

// client/src/pages/chat.tsx
import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuTrigger 
} from "@/components/ui/dropdown-menu";
import { 
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { 
  PlusCircle, 
  Send, 
  User, 
  Bot, 
  MoreVertical,
  Trash2,
  Edit3,
  MessageSquare,
  Crown,
  Zap,
  Star,
  Brain,
  Cpu
} from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import type { Message, Conversation } from "@shared/schema";

// Available AI Models
const AI_MODELS = [
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    description: "Schnell & ausgewogen (Google)",
    icon: Brain,
    color: "text-blue-500",
    tier: "free"
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    description: "Neuestes OpenAI-Modell (Aug 2025)",
    icon: Star,
    color: "text-green-600",
    tier: "pro"
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    description: "Omni-Modell Audio/Vision (OpenAI)",
    icon: Star,
    color: "text-green-500",
    tier: "ultra"
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    description: "Kostengünstig (OpenAI)",
    icon: Star,
    color: "text-green-400",
    tier: "free"
  },
  {
    id: "gemini-2.5-pro", 
    name: "Gemini 2.5 Pro",
    description: "Erweiterte Fähigkeiten (Google)",
    icon: Brain,
    color: "text-blue-600",
    tier: "ultra"
  },
  {
    id: "deepseek/deepseek-r1:free",
    name: "DeepSeek R1 (Free)",
    description: "Reasoning & Logik (DeepSeek)",
    icon: Cpu,
    color: "text-purple-500", 
    tier: "free"
  },
  {
    id: "deepseek-chat",
    name: "DeepSeek Chat",
    description: "Kostengünstig & leistungsstark",
    icon: Cpu,
    color: "text-purple-600",
    tier: "ultra"
  },
  {
    id: "google/gemini-2.0-flash:free",
    name: "Gemini 2.0 Flash (Free)",
    description: "Neueste Version kostenlos",
    icon: Brain,
    color: "text-green-500",
    tier: "free"
  }
];

export default function Chat() {
  const { user, isAuthenticated } = useAuth();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [selectedConversationId, setSelectedConversationId] = useState<string | null>(null);
  const [newMessage, setNewMessage] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedModel, setSelectedModel] = useState("gemini-2.5-flash");
  const messagesEndRef = useRef<HTMLDivElement>(null);
  
  // Guest chat state
  const [guestMessages, setGuestMessages] = useState<Array<{role: string, content: string, timestamp: Date}>>([]);

  // Fetch conversations (only for authenticated users)
  const { data: conversations = [] } = useQuery({
    queryKey: ["/api/conversations"],
    enabled: isAuthenticated,
  }) as { data: Conversation[] };

  // Fetch messages for selected conversation (only for authenticated users)
  const { data: messages = [] } = useQuery({
    queryKey: ["/api/conversations", selectedConversationId, "messages"],
    enabled: !!selectedConversationId && isAuthenticated,
  }) as { data: Message[] };

  // Create new conversation
  const createConversationMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest("POST", "/api/conversations", {
        title: "Neues Gespräch"
      });
      return response.json();
    },
    onSuccess: (newConversation) => {
      queryClient.invalidateQueries({ queryKey: ["/api/conversations"] });
      setSelectedConversationId(newConversation.id);
    },
  });

  // Send message
  const sendMessageMutation = useMutation({
    mutationFn: async (content: string) => {
      if (!selectedConversationId) {
        throw new Error("Keine Unterhaltung ausgewählt");
      }
      
      setIsGenerating(true);
      const response = await apiRequest("POST", `/api/conversations/${selectedConversationId}/messages`, {
        content,
        role: "user",
        model: selectedModel
      });
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ 
        queryKey: ["/api/conversations", selectedConversationId, "messages"] 
      });
      setNewMessage("");
      setIsGenerating(false);
    },
    onError: () => {
      setIsGenerating(false);
      toast({
        title: "Fehler",
        description: "Nachricht konnte nicht gesendet werden.",
        variant: "destructive",
      });
    },
  });

  // Guest chat mutation (for unauthenticated users)
  const guestChatMutation = useMutation({
    mutationFn: async (content: string) => {
      const response = await fetch('/api/chat/free', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ 
          message: content,
          model: selectedModel 
        }),
      });
      
      if (!response.ok) {
        throw new Error('Failed to send message');
      }
      
      return response.json();
    },
    onSuccess: (data) => {
      // Add AI response to guest messages
      setGuestMessages(prev => [...prev, {
        role: 'assistant',
        content: data.response,
        timestamp: new Date()
      }]);
      setNewMessage("");
      setIsGenerating(false);
    },
    onError: () => {
      setIsGenerating(false);
      toast({
        title: "Fehler",
        description: "Nachricht konnte nicht gesendet werden.",
        variant: "destructive",
      });
    },
  });

  // Delete conversation
  const deleteConversationMutation = useMutation({
    mutationFn: async (conversationId: string) => {
      await apiRequest("DELETE", `/api/conversations/${conversationId}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/conversations"] });
      if (selectedConversationId === selectedConversationId) {
        setSelectedConversationId(null);
      }
    },
  });

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, guestMessages]);

  // Auto-select first conversation
  useEffect(() => {
    if (conversations.length > 0 && !selectedConversationId) {
      setSelectedConversationId(conversations[0].id);
    }
  }, [conversations, selectedConversationId]);

  const handleSendMessage = () => {
    if (!newMessage.trim() || isGenerating) return;
    
    if (!isAuthenticated) {
      // Guest mode - use free chat
      setIsGenerating(true);
      // Add user message to guest messages
      setGuestMessages(prev => [...prev, {
        role: 'user',
        content: newMessage.trim(),
        timestamp: new Date()
      }]);
      guestChatMutation.mutate(newMessage.trim());
      return;
    }
    
    if (!selectedConversationId) {
      // Create new conversation first
      createConversationMutation.mutate();
      return;
    }
    
    sendMessageMutation.mutate(newMessage.trim());
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const getUserTier = () => {
    const tier = (user as any)?.subscriptionTier || 'free';
    switch (tier) {
      case 'pro': return { label: 'Pro', icon: Crown, color: 'text-yellow-500' };
      case 'ultra': return { label: 'Ultra', icon: Zap, color: 'text-purple-500' };
      default: return { label: 'Free', icon: Star, color: 'text-gray-500' };
    }
  };

  const userTier = getUserTier();

  return (
    <div className="flex h-screen bg-white">
      {/* Sidebar */}
      <div className="w-80 bg-gray-50 border-r border-gray-200 flex flex-col">
        {/* Header */}
        <div className="p-4 border-b border-gray-200">
          {isAuthenticated ? (
            <Button
              onClick={() => createConversationMutation.mutate()}
              className="w-full justify-start gap-2 bg-lopez-green hover:bg-lopez-green-dark"
              disabled={createConversationMutation.isPending}
            >
              <PlusCircle className="w-4 h-4" />
              Neues Gespräch
            </Button>
          ) : (
            <div className="text-center">
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Free Chat</h3>
              <Button 
                onClick={() => window.location.href = '/api/login'}
                className="w-full bg-lopez-green hover:bg-lopez-green-dark"
              >
                Anmelden für mehr Features
              </Button>
            </div>
          )}
        </div>

        {/* Conversations List (only for authenticated users) */}
        {isAuthenticated && (
          <ScrollArea className="flex-1 p-2">
            {conversations.map((conversation: Conversation) => (
            <div
              key={conversation.id}
              className={`group p-3 rounded-lg cursor-pointer mb-1 transition-colors ${
                selectedConversationId === conversation.id
                  ? 'bg-gray-200'
                  : 'hover:bg-gray-100'
              }`}
              onClick={() => setSelectedConversationId(conversation.id)}
            >
              <div className="flex items-center justify-between">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <MessageSquare className="w-4 h-4 text-gray-500" />
                    <span className="text-sm font-medium text-gray-900 truncate">
                      {conversation.title}
                    </span>
                  </div>
                  <p className="text-xs text-gray-500 truncate">
                    {conversation.updatedAt ? new Date(conversation.updatedAt).toLocaleDateString('de-CH') : ''}
                  </p>
                </div>
                
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="opacity-0 group-hover:opacity-100 h-8 w-8 p-0"
                    >
                      <MoreVertical className="w-4 h-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem>
                      <Edit3 className="w-4 h-4 mr-2" />
                      Umbenennen
                    </DropdownMenuItem>
                    <DropdownMenuItem
                      className="text-red-600"
                      onClick={() => deleteConversationMutation.mutate(conversation.id)}
                    >
                      <Trash2 className="w-4 h-4 mr-2" />
                      Löschen
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>
          ))}
          </ScrollArea>
        )}

        {/* User Info */}
        <div className="p-4 border-t border-gray-200">
          <div className="flex items-center gap-3">
            {(user as any)?.profileImageUrl ? (
              <img 
                src={(user as any).profileImageUrl} 
                alt="Profile" 
                className="w-8 h-8 rounded-full"
              />
            ) : (
              <div className="w-8 h-8 bg-lopez-green rounded-full flex items-center justify-center">
                <User className="w-4 h-4 text-white" />
              </div>
            )}
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-gray-900 truncate">
                {(user as any)?.firstName || (user as any)?.email}
              </p>
              <div className="flex items-center gap-1">
                <userTier.icon className={`w-3 h-3 ${userTier.color}`} />
                <span className={`text-xs ${userTier.color}`}>{userTier.label}</span>
              </div>
            </div>
          </div>
          
          {/* Minimal branding */}
          <div className="mt-3 text-center">
            <span className="text-xs text-gray-400">KI-Chat</span>
          </div>
        </div>
      </div>

      {/* Chat Area */}
      <div className="flex-1 flex flex-col">
        {(isAuthenticated && selectedConversationId) || !isAuthenticated ? (
          <>
            {/* Model Selector Header */}
            <div className="border-b border-gray-200 p-4">
              <div className="max-w-3xl mx-auto flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <Brain className="w-5 h-5 text-lopez-green" />
                  <span className="text-sm font-medium text-gray-700">AI-Modell:</span>
                  <Select value={selectedModel} onValueChange={setSelectedModel}>
                    <SelectTrigger className="w-[280px]" data-testid="model-selector">
                      <SelectValue placeholder="Modell auswählen" />
                    </SelectTrigger>
                    <SelectContent>
                      {AI_MODELS.map((model) => {
                        const ModelIcon = model.icon;
                        const userTier = (user as any)?.subscriptionTier || 'free';
                        const canUse = model.tier === 'free' || 
                                      (model.tier === 'ultra' && ['ultra', 'pro'].includes(userTier)) ||
                                      (model.tier === 'pro' && userTier === 'pro');
                        
                        return (
                          <SelectItem 
                            key={model.id} 
                            value={model.id}
                            disabled={!canUse}
                            data-testid={`model-option-${model.id}`}
                          >
                            <div className="flex items-center gap-2">
                              <ModelIcon className={`w-4 h-4 ${model.color}`} />
                              <div className="flex flex-col">
                                <span className="font-medium">{model.name}</span>
                                <span className="text-xs text-gray-500">{model.description}</span>
                              </div>
                              {!canUse && (
                                <Badge variant="outline" className="text-xs ml-auto">
                                  {model.tier === 'ultra' ? 'Ultra+' : 'Pro'}
                                </Badge>
                              )}
                            </div>
                          </SelectItem>
                        );
                      })}
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex items-center gap-2 text-xs text-gray-500">
                  <Cpu className="w-3 h-3" />
                  <span>Multi-AI</span>
                </div>
              </div>
            </div>
            
            {/* Messages */}
            <ScrollArea className="flex-1 p-6">
              <div className="max-w-3xl mx-auto space-y-6">
                {!isAuthenticated && (
                  <div className="text-center py-4 border-b border-gray-200 mb-6">
                    <h2 className="text-lg font-semibold text-gray-900">Free Chat</h2>
                    <p className="text-sm text-gray-600">Anmelden für erweiterte Funktionen und Gesprächsspeicher</p>
                  </div>
                )}
                
                {(isAuthenticated ? messages : guestMessages).map((message: any, index: number) => (
                  <div
                    key={message.id || index}
                    className={`flex gap-4 ${
                      message.role === 'user' ? 'justify-end' : 'justify-start'
                    }`}
                  >
                    {message.role === 'assistant' && (
                      <div className="w-8 h-8 bg-lopez-green rounded-full flex items-center justify-center flex-shrink-0">
                        <Bot className="w-4 h-4 text-white" />
                      </div>
                    )}
                    
                    <div className={`max-w-[70%] ${
                      message.role === 'user' 
                        ? 'bg-lopez-green text-white' 
                        : 'bg-gray-100 text-gray-900'
                    } rounded-2xl px-4 py-3`}>
                      <p className="text-sm whitespace-pre-wrap">{message.content}</p>
                      
                      {/* Quality indicators for assistant messages */}
                      {message.role === 'assistant' && (
                        <div className="flex gap-2 mt-2">
                          {message.confidenceScore && (
                            <Badge variant="outline" className="text-xs">
                              {message.confidenceScore}% sicher
                            </Badge>
                          )}
                          {message.isVerified && (
                            <Badge variant="outline" className="text-xs text-green-600">
                              Verifiziert
                            </Badge>
                          )}
                        </div>
                      )}
                    </div>
                    
                    {message.role === 'user' && (
                      <div className="w-8 h-8 bg-gray-300 rounded-full flex items-center justify-center flex-shrink-0">
                        <User className="w-4 h-4 text-gray-600" />
                      </div>
                    )}
                  </div>
                ))}
                
                {isGenerating && (
                  <div className="flex gap-4 justify-start">
                    <div className="w-8 h-8 bg-lopez-green rounded-full flex items-center justify-center">
                      <Bot className="w-4 h-4 text-white" />
                    </div>
                    <div className="bg-gray-100 rounded-2xl px-4 py-3">
                      <div className="flex gap-1">
                        <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                        <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{animationDelay: '0.1s'}}></div>
                        <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{animationDelay: '0.2s'}}></div>
                      </div>
                    </div>
                  </div>
                )}
                
                <div ref={messagesEndRef} />
              </div>
            </ScrollArea>

            {/* Input Area */}
            <div className="border-t border-gray-200 p-4">
              <div className="max-w-3xl mx-auto">
                <div className="flex gap-3 items-end">
                  <div className="flex-1">
                    <Input
                      value={newMessage}
                      onChange={(e) => setNewMessage(e.target.value)}
                      onKeyPress={handleKeyPress}
                      placeholder="Nachricht eingeben..."
                      disabled={isGenerating}
                      className="min-h-[44px] resize-none"
                    />
                  </div>
                  <Button
                    onClick={handleSendMessage}
                    disabled={!newMessage.trim() || isGenerating}
                    className="bg-lopez-green hover:bg-lopez-green-dark h-11 w-11 p-0"
                  >
                    <Send className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </div>
          </>
        ) : (
          /* Welcome Screen */
          <div className="flex-1 flex items-center justify-center">
            <div className="text-center max-w-md">
              <div className="w-16 h-16 bg-lopez-green rounded-full flex items-center justify-center mx-auto mb-4">
                <Bot className="w-8 h-8 text-white" />
              </div>
              <h2 className="text-2xl font-semibold text-gray-900 mb-2">
                Willkommen
              </h2>
              <p className="text-gray-600 mb-6">
                Starten Sie ein neues Gespräch oder wählen Sie eine bestehende Unterhaltung aus.
              </p>
              <Button
                onClick={() => createConversationMutation.mutate()}
                className="bg-lopez-green hover:bg-lopez-green-dark"
                disabled={createConversationMutation.isPending}
              >
                <PlusCircle className="w-4 h-4 mr-2" />
                Neues Gespräch starten
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
