// angular-client/src/app/components/layout/footer.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [RouterLink],
  template: `
    <footer class="footer">
      <div class="container">
        <div class="footer-grid">
          <div class="footer-brand">
            <div class="footer-logo">
              <div class="logo-icon">W</div>
              <span>wensday.ch</span>
            </div>
            <p class="footer-desc">
              Swiss AI chat platform for professional research and independent analysis.
            </p>
            <p class="footer-powered">Powered by <span>lopez.codes</span></p>
          </div>

          <div class="footer-col">
            <h4>Produkt</h4>
            <ul>
              <li><a routerLink="/chat">Chat</a></li>
              <li><a routerLink="/subscribe">Preise</a></li>
              <li><a routerLink="/">Features</a></li>
            </ul>
          </div>

          <div class="footer-col">
            <h4>Unternehmen</h4>
            <ul>
              <li><a routerLink="/about">Über uns</a></li>
              <li><a routerLink="/contact">Kontakt</a></li>
            </ul>
          </div>

          <div class="footer-col">
            <h4>Rechtliches</h4>
            <ul>
              <li><a routerLink="/privacy">Datenschutz</a></li>
              <li><a routerLink="/terms">AGB</a></li>
            </ul>
          </div>
        </div>

        <div class="footer-bottom">
          <p>© 2025 wensday.ch · Lopez Codes, CHE-316.025.450 · Münsingen, Switzerland 🇨🇭</p>
        </div>
      </div>
    </footer>
  `,
  styles: [`
    .footer {
      background: #111827;
      color: white;
      padding: 4rem 0 2rem;
      margin-top: 4rem;
    }
    .footer-grid {
      display: grid;
      grid-template-columns: 2fr 1fr 1fr 1fr;
      gap: 2rem;
      margin-bottom: 3rem;
    }
    @media (max-width: 768px) {
      .footer-grid { grid-template-columns: 1fr 1fr; }
    }
    @media (max-width: 480px) {
      .footer-grid { grid-template-columns: 1fr; }
    }
    .footer-logo {
      display: flex;
      align-items: center;
      gap: 0.625rem;
      margin-bottom: 0.875rem;
    }
    .logo-icon {
      width: 2rem;
      height: 2rem;
      background: var(--lopez-green);
      border-radius: 0.375rem;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 700;
      font-size: 0.875rem;
    }
    .footer-logo span { font-size: 1.125rem; font-weight: 700; }
    .footer-desc {
      color: #9ca3af;
      font-size: 0.875rem;
      line-height: 1.6;
      margin-bottom: 0.5rem;
    }
    .footer-powered {
      font-size: 0.8125rem;
      color: #6b7280;
    }
    .footer-powered span { color: var(--lopez-green); font-weight: 600; }
    .footer-col h4 {
      font-weight: 600;
      margin-bottom: 1rem;
      font-size: 0.9375rem;
    }
    .footer-col ul { list-style: none; display: flex; flex-direction: column; gap: 0.5rem; }
    .footer-col a {
      color: #9ca3af;
      font-size: 0.875rem;
      text-decoration: none;
      transition: color 0.2s;
    }
    .footer-col a:hover { color: var(--lopez-green); }
    .footer-bottom {
      border-top: 1px solid #1f2937;
      padding-top: 1.5rem;
      text-align: center;
      color: #6b7280;
      font-size: 0.8125rem;
    }
  `]
})
export class FooterComponent {}

// client/src/components/layout/footer.tsx
import { SiX, SiLinkedin, SiGithub } from "react-icons/si";
import { Link } from "wouter";

export default function Footer() {
  return (
    <footer className="bg-gray-900 text-white py-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid md:grid-cols-4 gap-8">
          <div className="space-y-4">
            <div className="flex items-center space-x-2">
              <div className="w-8 h-8 bg-lopez-green rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-sm">W</span>
              </div>
              <span className="text-xl font-bold">wensday.ch</span>
            </div>
            <p className="text-gray-400 leading-relaxed">
              Swiss AI chat platform for professional research and independent analysis.
            </p>
            <div className="flex items-center space-x-2">
              <span className="text-sm text-gray-400">Powered by</span>
              <span className="text-lopez-green font-semibold">lopez.codes</span>
            </div>
          </div>

          <div>
            <h4 className="font-semibold mb-4">Product</h4>
            <ul className="space-y-2 text-gray-400">
              <li><a href="#features" className="hover:text-lopez-green transition-colors">Features</a></li>
              <li><a href="#pricing" className="hover:text-lopez-green transition-colors">Pricing</a></li>
              <li><a href="#" className="hover:text-lopez-green transition-colors">API Access</a></li>
              <li><a href="#" className="hover:text-lopez-green transition-colors">Multiverse</a></li>
            </ul>
          </div>

          <div>
            <h4 className="font-semibold mb-4">Company</h4>
            <ul className="space-y-2 text-gray-400">
              <li><Link href="/about" className="hover:text-lopez-green transition-colors">About</Link></li>
              <li><Link href="/contact" className="hover:text-lopez-green transition-colors">Kontakt</Link></li>
              <li><a href="#partners" className="hover:text-lopez-green transition-colors">Partners</a></li>
              <li><Link href="/contact" className="hover:text-lopez-green transition-colors">Careers</Link></li>
            </ul>
          </div>

          <div>
            <h4 className="font-semibold mb-4">Support</h4>
            <ul className="space-y-2 text-gray-400">
              <li><Link href="/contact" className="hover:text-lopez-green transition-colors">Documentation</Link></li>
              <li><Link href="/contact" className="hover:text-lopez-green transition-colors">Help Center</Link></li>
              <li><Link href="/privacy" className="hover:text-lopez-green transition-colors">Datenschutz</Link></li>
              <li><Link href="/terms" className="hover:text-lopez-green transition-colors">AGB</Link></li>
            </ul>
          </div>
        </div>

        <div className="border-t border-gray-800 mt-12 pt-8 flex flex-col md:flex-row justify-between items-center">
          <p className="text-gray-400 text-sm">
            © 2024 wensday.ch. All rights reserved. Made in Switzerland 🇨🇭
          </p>
          <div className="flex items-center space-x-4 mt-4 md:mt-0">
            <span className="text-gray-400 text-sm">Follow us:</span>
            <a href="#" className="text-gray-400 hover:text-lopez-green transition-colors">
              <SiX className="w-5 h-5" />
            </a>
            <a href="#" className="text-gray-400 hover:text-lopez-green transition-colors">
              <SiLinkedin className="w-5 h-5" />
            </a>
            <a href="#" className="text-gray-400 hover:text-lopez-green transition-colors">
              <SiGithub className="w-5 h-5" />
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
}
